/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/footer/AppFooter.vue')['default']
    AppHeader: typeof import('./components/header/AppHeader.vue')['default']
    DarkToggler: typeof import('./components/header/DarkToggler.vue')['default']
    DriverButton: typeof import('./components/header/DriverButton.vue')['default']
    GifGenerator: typeof import('./components/GifGenerator.vue')['default']
    ImageEditor: typeof import('./components/editor/ImageEditor.vue')['default']
    ImageGallery: typeof import('./components/ImageGallery.vue')['default']
    LanguageDropdown: typeof import('./components/header/LanguageDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextboxEditor: typeof import('./components/editor/TextboxEditor.vue')['default']
  }
}
